CC = gcc
CXX = g++
AR = ar

ifeq ($(shell uname),Darwin)
     PLATFORM_MAC = 1
endif

ifdef PLATFORM_MAC
    DLIB_EXT = dylib
    DLIB_PATH = DYLD_LIBRARY_PATH
else
    DLIB_EXT = so
    DLIB_PATH = LD_LIBRARY_PATH
endif

CFLAGS = -Wall -Werror -Wunused-parameter -Wshadow
ifdef DEBUG
    CFLAGS += -g
    LDFLAGS += -g
else
    CFLAGS += -O3
endif

CFLAGS += -I$(ROOTDIR) -pedantic
ifdef ANSI
    CFLAGS += -ansi
endif

CXXFLAGS = $(CFLAGS)

BUILDDIR = $(ROOTDIR)/build
