CC = gcc
CXX = g++
AR = ar

ifeq ($(shell uname),Darwin)
     PLATFORM_MAC = 1
endif

ifdef PLATFORM_MAC
    DLIB_EXT = dylib
    DLIB_PATH = DYLD_LIBRARY_PATH
else
    DLIB_EXT = so
    DLIB_PATH = LD_LIBRARY_PATH
endif

CFLAGS = -Wall -Werror -Wunused-parameter -Wshadow
ifdef DEBUG
    CFLAGS += -g
else
    CFLAGS += -O3
endif

ALL_CFLAGS = -I$(ROOTDIR) -pedantic $(CFLAGS)
ifdef ANSI
    ALL_CFLAGS += -ansi
endif

CXXFLAGS = $(CFLAGS)
ALL_CXXFLAGS = $(ALL_CFLAGS)

BUILDDIR = $(ROOTDIR)/build
